### ISSUE TITLE
Getting blank color on Linux

### ISSUE THREAD

**Issue by Igneom** [hazdryx/FastBitmap#2]
The get and set methods seem to work normally on windows, but on linux, the get method always returns a blank color.

As far as my understanding of the code goes, you seem to be initializing the BaseBitmap with a pointer to the Data array, so it can be a direct access to the pixels on the Bitmap, and that seems to be causing an issue with the Graphics.DrawImage method, which seems to not be drawing at all on the BaseBitmap when the code is ran on linux. 

I'm using Ubuntu 20.04, and verified that If you just call DrawImage on a regular bitmap, it works as expected with no issues, but when creating a FastBitmap object, passing a Bitmap object as argument, the Data array is entirely comprised of zeros. If you use any of the set methods, it works just fine, which leads to DrawImage being the culprit.

I'm not sure if it's possible, but instead of getting the pointer of the Data array, and embedding in the BaseBitmap, do the opposite, get the Data array to point to the BaseBitmap internal data, that could be a solution, and also would remove the need to draw the image parameter on the BaseBitmap. But i'm not knowledgeable enough to know if that's a possibility. But I will try some other possible solutions in the mean time, while I wait for your answer.

**Comment by hazdryx** [comment]
I wonder if the pointer on linux isn't being set properly when initiating the BaseBitmap. I have a couple of things that I think will fail if you wanna check them out. 

1. Does setting data using FastBitmap.Set(x, y) to the FastBitmap actually have a change on the BaseBitmap using BaseBitmap.GetPixel(x, y).
2. Do any of the other Graphics methods work like Graphics.FillRect?

If this assumtion is correct, maybe changing from .NET Standard 2.0 to .NET 5 might help if this issue was found on Microsoft's end.

**Comment by Igneom** [comment]
I've updated the develop branch on my fork, to have more tests, which I believe should represent more accurate regular usage of the library, and at the same time, be easier to test with other instances of the FastBitmap object. I'm not entirely familiar with the usage of xUnit and if there was a better way to do the same.

On linux, the already existing tests, where you filled manually the Data array, all pass successfully. Tests using the Image constructor fail when trying to get the values. And tests using the Image constructor and manually setting each pixel afterwards on the FastBitmap object, all pass, except a new one where it verifies if the values reflect on the BaseBitmap.

Weirdly, some of the Tests using only the Image constructor, also fail on Windows, again, I'm not that used to xUnit, nor the int representation of argb values, but if I'm not mistaken, they are failing due to one returning signed ints, while the other one returns an unsigned representation, or something like that.

I've also verified manually if FillRect is changing anything on the Data array, and it isn't, even while using .NET 5, again, only on linux, on windows it's working correctly.

I was also thinking that it may have been something missing on linux, which may have been causing the issue in the first place, but not only the project where I was using your library, was deployed self contained, which should have all the dependencies on it. But now testing the library inside Rider directly on linux, should've not have any issues with missing dependencies, as far as I'm aware.

And I still haven't managed to think on a possible solution to this issue, that doesn't make it lose by a lot, the performance that it has, when it's working normally.

**Comment by Igneom** [comment]
I discovered that some of the issues with the tests on windows, was due to me setting the coordinates on a wrong order. which corrected all issues with the tests on windows.

The solution was kind of what I mentioned at first, but instead, copying the data from the Image passed on the constructor, to the Data array, directly, while still keeping the original link to BaseBitmap.

All tests passed okay, benchmark showed around 22,000% increase in performance, it worked correctly on my project, so overall, everything seems to be ok now.

**Comment by hazdryx** [comment]
This issue has been resolved, but I believe there is still an issue with Graphics operations on linux? If so we can start a new issue for this with better details on that specifically. 

I'll have a Ubuntu instance up soon, so I can assess what is going on as well.

**Comment by hazdryx** [comment]
I have a Ubuntu 20.04 (LTS) instance working and created a new issue.
